version: "3.9"

services:
  webportal:
    depends_on:
      - backend
    image: webportal
    build:
      context: ui/react
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  backend:
    container_name: djnago_backend
    build:
      context: cmd/TechRxProject
      dockerfile: ./Dockerfile
    image: techrx-api-service
    ports:
      - 8000:8000

volumes:
  mssqldata:
