version: "3.9"

services:
  db:
    container_name: sqlserverdb
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      # - MSSQL_SA_PASSWORD=yourStrong(!)Password
    env_file:
      - "env/development.env"
    ports:
      - 1433:1433
    volumes:
      - ./temp/mssqldata:/var/opt/mssql
    # platform: linux/amd64

  webportal:
    image: webportal
    build:
      context: ui/web-portal
      dockerfile: ./Dockerfile
    ports:
      - 80:80

volumes:
  mssqldata:
