version: "3.8"

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql_server_db
    ports:
      - 1433:1433
    env_file:
      - env/development.env
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./temp/mssqldata:/var/opt/mssql

  webportal:
    depends_on:
      - backend
    image: webportal
    build:
      context: ui/portal
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  backend:
    container_name: django_backend
    build:
      context: cmd/TechRxProject
      dockerfile: ./Dockerfile
    image: techrx-api-service
    ports:
      - 8000:8000

  chat:
    container_name: chat
    build:
      context: cmd/pharma_connect_chatbot
      dockerfile: ./Dockerfile
    image: pharma_chatbot
    ports:
      - 5005:5005

volumes:
  mssqldata:
