version: "3.9"

services:
  db:
    container_name: sqlserverdb
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - "env/development.env"
    ports:
      - 1433:1433
    volumes:
      - ./temp/mssqldata:/var/opt/mssql

  webportal:
    image: webportal
    build:
      context: ui/web-portal
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  backend:
    container_name: djnago_backend
    build:
      context: cmd/TechRxProject
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

volumes:
  mssqldata:
